- AzureCP.sln
- AzureCP/AuthenticationHelper.cs
- AzureCP/AzureCP.cs
- AzureCP/AzureCP.csproj
- AzureCP/AzureCPConfig.cs
- AzureCP/AzureCPLogging.cs
- AzureCP/Package/Package.package
- AzureCP/Properties/AssemblyInfo.cs
- AzureCP/packages.config
- Fixed async management
- Added locking when setting access token 
- Implemented retry while getting group membership
> Publish AzureCP v10

- AzureCP/AzureCP.cs
- AzureCP/AzureCPConfig.cs
- AzureCP/TEMPLATE/ADMIN/AzureCP/AzureCPSettings.aspx
- AzureCP/TEMPLATE/ADMIN/AzureCP/AzureCPSettings.aspx.cs
- AzureCP/TEMPLATE/ADMIN/AzureCP/AzureCPSettings.aspx.designer.cs
Good evening,
I were able to prepare some code that compiles correctly.
Unfortunatly i am not able to test the result as:
- i can't sign the assembly (complains that Nito.AsyncEx is not strong named)
- i suppose the assembly should be in the GAC to be used by sharepoint
Nevertheless i think the logic to filter shadow accounts is sound (naturaly i did it :D).
Would consider merging it in AzureCP?
Cédric
PS: this is one part of the issue #8 i raised.
> Get Verified Domains and Skip Shadow Users

- AzureCP/AzureCP.csproj
- AzureCP/Package/Package.package
- CHANGELOG.md
* Include System.ValueTuple.dll v4.0.1.0 From NuGet package System.ValueTuple v4.5.0
> Publish AzureCP v15.1

- AzureCP.Tests/EntityTestsBase.cs
- AzureCP.Tests/UnitTestsHelper.cs
- AzureCP/AzureCP.cs
- CHANGELOG.md
- DevOps-ApplyDTLArtifacts.yml
- DevOps-Compile.yml
* Fix a bug where search fails if input contains a '{'
> Publish AzureCP 15.3

- AzureCP/AzureCP.cs
- AzureCP/AzureCP.csproj
- CHANGELOG.md
* Fix error when earching users with a single quote in the people picker - https://github.com/Yvand/AzureCP/issues/88
* Use batch requests when relevant to optimize network performance
* Avoid potential null reference exception in method AzureCP.ProcessAzureADResults() and ensure that method AzureCP.QueryAzureADTenantAsync() never returns null
* Update target framework to v4.6.1
* Update NuGet package Microsoft.Graph 1.21.0 -> Microsoft.Graph 3.8.0
* Update NuGet package Microsoft.IdentityModel.Clients.ActiveDirectory 5.2.6 -> Microsoft.IdentityModel.Clients.ActiveDirectory 5.2.7
> Publish v17

- AzureCP/AzureCP.cs
- AzureCP/AzureCP.csproj
* Configure advanced query to fix https://github.com/Yvand/AzureCP/issues/166
> Set advanced query

- AzureCP/AzureCP.csproj
- AzureCP/ClaimTypeConfig.cs
* Fixes the properties of the identity claim type not updated - https://github.com/Yvand/AzureCP/issues/165
> Fix idctype notupdated

- AzureCP/ClaimTypeConfig.cs
> Revert "Fix idctype notupdated"

- AzureCP/AzureCP.cs
- AzureCP/AzureCP.csproj
> Revert "Set advanced query"

- AzureCP/ClaimTypeConfig.cs
* Fixes the properties of the identity claim type not updated - https://github.com/Yvand/AzureCP/issues/165
> Fix idctype notupdated (reopened to update dev branch)

- AzureCP/AzureCP.cs
* Configure advanced query to fix https://github.com/Yvand/AzureCP/issues/166
> Set advanced query (reopened to update dev branch)

- AzureCP.Tests/AzureCP.Tests.csproj
- AzureCP/AzureCP.csproj
- AzureCP/Package/Package.package
- CHANGELOG.md
* Update .NET Framework dependency to .NET 4.8
* Update reference on Microsoft.SharePoint.dll to use the one published with SharePoint Subscription RTM
* Update minimum SharePoint Product Version from 15.0 to 16.0
> Update dependencies and reference to Microsoft.SharePoint.dll

- AzureCP/Package/Package.package
- CHANGELOG.md
* Change the deployment server type of the wsp solution to "ApplicationServer"
> Change the deploymentServerType of the wsp solution to ApplicationServer

- CHANGELOG.md
- Yvand.EntraCP/TEMPLATE/ADMIN/EntraCP/GlobalSettings.ascx.cs
- Yvand.EntraCP/Yvand.EntraClaimsProvider/Configuration/EntraIDProviderConfiguration.cs
- Yvand.EntraCP/Yvand.EntraClaimsProvider/Configuration/EntraIDTenant.cs
* Improve the management of tenant credentials, including new helpers to renew the client secret of certificate using PowerShell
> Update credentials management

- CHANGELOG.md
- Yvand.EntraCP/TEMPLATE/ADMIN/EntraCP/ClaimTypesConfig.ascx.cs
Fix https://github.com/Yvand/EntraCP/issues/219
> Fix "Edit" links fail to work on the "Claim types configuration" page

- CHANGELOG.md
- Yvand.EntraCP/TEMPLATE/ADMIN/EntraCP/GlobalSettings.ascx.cs
- Yvand.EntraCP/Yvand.EntraClaimsProvider/Configuration/ClaimsProviderConstants.cs
- Yvand.EntraCP/Yvand.EntraClaimsProvider/Configuration/EntraIDTenant.cs
* Fix the connection to Microsoft Graph not working when the tenant is hosted in a national cloud
> Set scope correctly for national clouds

- CHANGELOG.md
- Yvand.EntraCP/Package/Package.package
- Yvand.EntraCP/Yvand.EntraCP.csproj
- assembly-bindings.config
* Update Azure.Identity from 1.10.4 to 1.11.2
* Update Microsoft.Graph from 5.44.0 to 5.49.0
> Bump all dependencies

- CHANGELOG.md
- Yvand.EntraCP/Yvand.EntraClaimsProvider/Configuration/ClaimsProviderConstants.cs
- Yvand.EntraCP/Yvand.EntraClaimsProvider/Configuration/EntraIDProviderConfiguration.cs
* Fix an ArgumentNullException in a very rare scenario where ClaimsPrincipal.Identity is null
* Add helper methods to get/delete a tenant in the configuration
> Fix ArgumentNullException in OperationContext and add a helper

- CHANGELOG.md
- Yvand.EntraCP.Tests/BasicConfigurationTests.cs
- Yvand.EntraCP.Tests/GuestAccountsUPNTests.cs
- Yvand.EntraCP/Yvand.EntraClaimsProvider/Configuration/ClaimsProviderConstants.cs
- Yvand.EntraCP/Yvand.EntraClaimsProvider/EntraIDEntityProvider.cs
* Fix a validation issue that impacted guest users, when the identifier property for guest users is the UserPrincipalName
> fix guest users validation issue

- CHANGELOG.md
- Yvand.EntraCP/Yvand.EntraClaimsProvider/Configuration/ClaimsProviderConstants.cs
- Yvand.EntraCP/Yvand.EntraClaimsProvider/Configuration/EntraIDProviderConfiguration.cs
- Yvand.EntraCP/Yvand.EntraClaimsProvider/EntraIDEntityProvider.cs
* Add property AllowedGroupMembersRequestPageSize, to set the page size of the requests that get the users members of the allowed groups (set in property RestrictSearchableUsersByGroups)
> Add property AllowedGroupMembersRequestPageSize
